on: [push, pull_request]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on Centos stream 9 on aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: alessandrocarminati/run-on-arch-action@v2.2.2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: CS9

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          shell: /bin/sh
          install:
               yum groupinstall -y "Development Tools" && yum install -y git libuuid-devel openssl-devel acpica-tools python3;\
               ln -s /usr/bin/python3 /usr/bin/python && chmod +x /usr/local/bin/build.sh
               
          run: |
            cat /etc/os-release 
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
